export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN'
}

export enum OrderStatus {
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  IN_TRANSIT = 'IN_TRANSIT',
  SHIPPING = 'SHIPPING',
  DELIVERED = 'DELIVERED',
  RETURNED_BP06 = 'RETURNED_BP06',
  CANCELLED = 'CANCELLED'
}

export enum OrderItemStatus {
  PENDING = 'PENDING',
  PREPARED = 'PREPARED',
  IN_PRODUCTION = 'IN_PRODUCTION',
  QC_PENDING = 'QC_PENDING',
  QC_PASSED = 'QC_PASSED',
  QC_FAILED = 'QC_FAILED'
}

export enum FulfillmentStatus {
  AWAITING_DEPOSIT = 'AWAITING_DEPOSIT',
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  AT_WORKSHOP = 'AT_WORKSHOP',
  QUALITY_INSPECTION = 'QUALITY_INSPECTION',
  PACKAGED = 'PACKAGED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  RETURNING = 'RETURNING',
  RETURNED_RECEIVED = 'RETURNED_RECEIVED',
  TRANSFERRED_BP06 = 'TRANSFERRED_BP06'
}

export enum PaymentStatus {
  UNPAID = 'UNPAID',
  PARTIALLY_PAID_DEPOSIT_50 = 'PARTIALLY_PAID_DEPOSIT_50',
  PAID_FULL = 'PAID_FULL',
  REFUNDED = 'REFUNDED'
}

export enum PaymentMode {
  DEPOSIT_50 = 'DEPOSIT_50',
  FULL_PAYMENT = 'FULL_PAYMENT'
}

export enum PaymentMethod {
  VIETQR = 'VIETQR',
  VNPAY = 'VNPAY',
  MOMO = 'MOMO',
  COD = 'COD'
}
